name       : libxml++
version    : 5.0.3
release    : 6
source     :
    - https://download.gnome.org/sources/libxml++/5.0/libxml++-5.0.3.tar.xz : 13074f59e3288a378cafe9e6847df17f764c23fa29bc94f3305b8bf81efb2cf7
license    : LGPL-2.1-or-later
component  : programming.library
summary    : C++ bindings to libxml2
description: |
    C++ bindings to libxml2
builddeps  :
    - pkgconfig(glibmm-2.4)
    - pkgconfig(libxml-2.0)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
