name       : libxml++
version    : 2.40.1
release    : 1
source     :
    - http://ftp.gnome.org/pub/GNOME/sources/libxml++/2.40/libxml++-2.40.1.tar.xz : 4ad4abdd3258874f61c2e2a41d08e9930677976d303653cd1670d3e9f35463e9
license    : LGPL-2.1
summary    : C++ bindings to libxml2
description: |
    C++ bindings to libxml2
builddeps  :
    - pkgconfig(glibmm-2.4)
    - pkgconfig(libxml-2.0)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
