name       : libxml++
version    : 2.42.0
release    : 3
source     :
    - https://download.gnome.org/sources/libxml++/2.42/libxml++-2.42.0.tar.xz : 3d032aede98a033eb5e815b4bfa9fa7b4e745268e6fd1ce8b1d0f70bcaf4736d
license    : LGPL-2.1-or-later
component  : programming.library
summary    : C++ bindings to libxml2
description: |
    C++ bindings to libxml2
builddeps  :
    - pkgconfig(glibmm-2.4)
    - pkgconfig(libxml-2.0)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
